### ISSUE TITLE
vk.com doesn't work anymore

### ISSUE THREAD

**Issue by sandoxy** [tobykurien/WebApps#101]
Hi, 

since version 2.15. vk.com didn't work, so I had to use 2.13. Since today it doesn't work with 2.13 either. There is an error message saying: website not available, could not load. net:err_too_many_redirects

Is there a pissibility to fix it?

Thanks

**Comment by tobykurien** [comment]
I didn't try logging in, but I am able to load vk.com using v2.16

**Comment by sandoxy** [comment]
Thanks you for yor answer. During the last view days it started to work again. But the version v2 16 keeps logging me out everytime I restart the app. Now I use v2.13, but it logs me out view times a day either.
