### ISSUE TITLE
Cert changes repeatedly showing up on Google News

### ISSUE THREAD

**Issue by tobykurien** [tobykurien/WebApps#108]

**Comment by troopermax** [comment]
Seeing this on GitHub as well - looks like it was just a routine certificate update and the old certificate is now expired, but it keeps showing me the old/new certificates on every GitHub page load.

**Comment by troopermax** [comment]
New F Droid version had option to accept certificate, but it was still popping up again on every page load while navigating GitHub. However, once I went back to the web app selection screen and then returned to GitHub, the acceptance of the certificate change seemed to take effect and it stopped asking me to accept it again.

Like that you've been working on this feature. Might also be neat to log all the certificates that have been seen from a site to give a viewable certificate history.
