### ISSUE TITLE
saving as webapp doesn't do anything

### ISSUE THREAD

**Issue by ericfont** [tobykurien/WebApps#11]
I got your app via fdroid.  I opened https://facebook.com, but when I went to save as "Facebook", nothing happens.  When I navigate back to front page of your app, I still see a bunch of "NULL" apps, and clicking any just crashes program.  Am I doing something wrong?  Or is that save behavior not implemented?  I'm on galaxy s3 with CyanogenMod 12 nightly.

**Comment by rigid** [comment]
:+1:

**Comment by DoctorJellyface** [comment]
+1

**Comment by tobykurien** [comment]
Thanks for reporting. Save is implemented (for example, try by visiting a new site). It also is meant to behave as an "edit", so that any 3rd party blocking changes you make is saved to the same webapp. Perhaps a library update has broken the functionality - I will look into this.

**Comment by tobykurien** [comment]
Seems to be an issue with the f-droid build of the app - mistake in the gradle build file.

**Comment by tobykurien** [comment]
closing, see https://github.com/tobykurien/WebApps/issues/15
