### ISSUE TITLE
[FR] Support multiple webapp instances

### ISSUE THREAD

**Issue by eggithub** [tobykurien/WebApps#111]
First off, you are doing a really nice job with this app. I have been looking for an app like this for ages.

Feature request: Support multiple webapp instances
Now everytime I open a link via the homescreen, it overwrites the previous webapp bacause there can run only one instance of the program. If you could create a new instance with each webapp you could switch between webapps. For example, an app called "unNative" does almost the same and supports multiple instances.

Would also like to have more control over cookies, for example to be able to keep them.

Keep up the good work!

Cheers!

E.

**Comment by ildar** [comment]
I'm not a Java programmer but I'd say that entering intents per WebApp
should be enough, see e.g. OctoDroid as a working example

**Comment by ildar** [comment]
Or... emm... Activities? Please correct me

**Comment by eggithub** [comment]
What I mean is that you'd be able to open a link as a new program instance. So for example when you look at your list op running apps that each website runs in its own webview instance.

I'm not a software programmer so I hope I describe this correctly.

Cheers!

**Comment by tobykurien** [comment]
Yep, got what you mean. It might even be nice to have the option to open webapps from the webapps list into new activities (screens) as well.
