### ISSUE TITLE
FR: Disable https for local network

### ISSUE THREAD

**Issue by gerroon** [tobykurien/WebApps#113]
Hi

Can you please disable tls check for local network use? I appreciate the commitment to the security, but for internal test without proper ssl schemes, it does not make much sense.

**Comment by tobykurien** [comment]
What do you mean by 'internal test'? Are you testing WebApps or an internal site? If the latter, why not use a different browser?

**Comment by gerroon** [comment]
I am trying to use this app for webapps hosted on the internal network. I like your app because it is more tailored for containing the site, whle other apps just seem to add a shortcut. I also do not want to use chrome because I do not want chrome to contantly phone home.

**Comment by tobykurien** [comment]
I would suggest that those internal sites should run on https as well, to prevent compromised machines or locally running malware from sniffing the traffic. You can use self-signed certs, browsers and WebApps show a warning, you save the cert and it works.

**Comment by ildar** [comment]
totally right. 👍

**Comment by fanthos** [comment]
Another way to do this:
Get a free domain, and you can obtain free cert from letsencrypt(certbot).

**Comment by gerroon** [comment]
Now I am being asked for a feature :)
