### ISSUE TITLE
Webapp uses wrong icon

### ISSUE THREAD

**Issue by esmoak** [tobykurien/WebApps#118]
Webapps v2.17 from F-Droid
Android 7.1.1

I deleted the Reddit webapp that was preconfigured.

I set a web app for: https://freelibrary.overdrive.com/

No matter how I try to configure it, the webapp uses the orange reddit icon on the main webapps screen. It will load the correct icon to the right of the back arrow on the top, but when I exit the webapp it still shows the reddit icon.

I've restarted the app, reconfigured the webapp, restarted phone, etc. No solution.

Thanks.

Edit: I cleared the phone's cached data but the reddit logo reappeared for the overdrive webapp after the icons regenerated.

It's the smaller version of this image, basically: https://i.redd.it/rq36kl1xjxr01.png

Edit 2: I resolved this by running LTE Cleaner from the IzzyOnDroid repo. It must have cleaned some type of cache. My icons are normal now.

Still, it's probably a bug? Leaving issue open for now unless you want to close it.

**Comment by tobykurien** [comment]
Thanks for the updates. Yes it is a bug - if you delete a webapp and add another one, it re-uses the icon of the deleted one, and doesn't replace it unless a higher-res icon is supplied. So I'll make it that it deletes the favicon everytime you launch a webapp, so that it can keep it updated.
