### ISSUE TITLE
Is WebApps built off of Bromite

### ISSUE THREAD

**Issue by trymeouteh** [tobykurien/WebApps#129]
And if not could you strongly consider? Bromite is a degoogled chromium browser for android.

**Comment by tobykurien** [comment]
No, WebApps uses the built-in Android WebView. What would be the advantage of using Bromite?

**Comment by trymeouteh** [comment]
Privacy. No google tracking code. Unless Andriod WebView is degoogled by default.

**Comment by tobykurien** [comment]
Yes Android WebView is open source and part of AOSP.

**Comment by trymeouteh** [comment]
So Webapps isnt a browser per say but uses the AOSP built in browser to render the webapps?

Is the Andriod WebView always up to date like Chrome or Firefox is? Or are updates not regular?

**Comment by tobykurien** [comment]
That's correct. Android WebView is updated via google play store.

**Comment by trymeouteh** [comment]
How does Andriod WebView update on devices without GAPPs like LineAgeOS. I download WebApps through F-Driod.

**Comment by tobykurien** [comment]
You can use Yalp to update Android System WebView

**Comment by trymeouteh** [comment]
Would it be more secure to copy the Andriod WebView into WebApps and then update the version of Chromium constantly to ensure users are using the latest versions. Using outdated browsers is not secure and outdated browsers can contain vulnerabilities.

Or will the Andriod WebView be updated regularly with Andriod system updates?

**Comment by sm4rk0** [comment]
When you [install Bromite System WebView](https://github.com/bromite/bromite/wiki/Installing-SystemWebView), WebApps will automatically use it. It's up to you, the phone user to update the system WebView. Maybe you're talking about available options for manually tweaking the [User Agent](https://github.com/tobykurien/WebApps/issues/69) within WebApps?

**Comment by trymeouteh** [comment]
> When you [install Bromite System WebView](https://github.com/bromite/bromite/wiki/Installing-SystemWebView), WebApps will automatically use it. It's up to you, the phone user to update the system WebView. Maybe you're talking about available options for manually tweaking the [User Agent](https://github.com/tobykurien/WebApps/issues/69) within WebApps?

Good to know. This William work them since the Bromide System Web view has regular updates on FDriod.

How does one tell what system! Web view engine/browser are they using in WebApps?

**Comment by sm4rk0** [comment]
If you open https://html5test.com/ from WebApps you should see "You are using Chromium WebView 71..." if you've installed latest (as of March 18) Bromite System WebView via F-Droid. Of course, check that WebApps UserAgent is set to "Default".

**Comment by trymeouteh** [comment]
I tried going to https://html5test.com/ in webapps on a device that had Bromite webview and another device that did not have Bromite Webview or Bromite itself and I found that they said the same thing that I am running "Chromium WebView 72"

**Comment by sm4rk0** [comment]
Strange... It's similar here. I have Bromite System WebView 73.0.3683.82 installed, but it is still detected as Chromium WebView 71 (Chrome/71.0.3578.99). That was the last Android System WebView version I had before replacing it with Bromite. When I reinstall Android System WebView, the version reported is updated to that one. After uninstalling it, the version is 71.x again. Version can be checked with [WebView Test](https://play.google.com/store/apps/details?id=com.snc.test.webview2&hl=en_US), too.

Sorry for offtopic. Maybe we should open a [Bromite issue](https://github.com/bromite/bromite/issues)?

**Comment by sm4rk0** [comment]
Just to conclude:

https://github.com/bromite/bromite/issues/138
> This is by design, as an anti-fingerprinting mitigation technique.

https://github.com/bromite/bromite/issues/162
> This is by design. in Bromite user-agents are fixed and do not report the real phone model or browser version/build as a fingerprinting mitigation.

**Comment by beerisgood** [comment]
This issue is already closed, but Bromite also include security stuff from GrapheneOS - known as CopperheadOS

So Bromite would a much better idea then using (sometime and on a lot devices) a old and less secure webview
