### ISSUE TITLE
Feature Request: Allow Location Option

### ISSUE THREAD

**Issue by trymeouteh** [tobykurien/WebApps#131]
Please add option for each webapp to allow it to get the device location and an option which it will as the user in the browser when the website it requesting the user location to ask the user if it will allow or block the location request.

This way I will be able to use Google Maps, Skip the Dishes easier. Please make this optional and disabled by default.

**Comment by Alexanderlll** [comment]
i need this too, great idea

**Comment by Friptick** [comment]
Uhhh. Ahem. [clears throat as politely as possible] Any news on this one?

**Comment by tobykurien** [comment]
Similar issue to #38 - it's a privacy concern. See the discussion there.

**Comment by Friptick** [comment]
OK, makes sense now. Relevant explanation for the record:

> Once WebApps is given permission to camera/microphone/location, then the system WebView will have access to these, regardless of which site is loaded.

**Comment by tobykurien** [comment]
FYI, I have decided to implement this anyway (https://github.com/tobykurien/WebApps/commit/61c159f852b906a28e29c8ad785a9163b9a7c4b9). The paranoid can leave location permission off, and there is a per-app option to allow or deny permission.
