### ISSUE TITLE
white/light favicon causes invisible buttonbar

### ISSUE THREAD

**Issue by zmrh** [tobykurien/WebApps#135]
The buttonbar in recent releases changes colour based on site's icon, which looks very nice in general.

However, when the icon's colours are white or light, the white buttons become invisible.

try for instance:
https://www.bellingcat.com

**Comment by zmrh** [comment]
![Screenshot_2019-03-28-19-24-10](https://user-images.githubusercontent.com/24855951/55183675-a06ab900-5190-11e9-941e-f0f57621ee72.png)

**Comment by tobykurien** [comment]
Yup, I have noticed it too. Thanks for reporting.

**Comment by trymeouteh** [comment]
A suggestion if to add a border around the icon to fix the seam.

**Comment by zmrh** [comment]
@trymeouteh it also affects the system bar on the top. Guess it would be better to avoid certain colour ranges perhaps.
