### ISSUE TITLE
Ugly Icons in Webapps

### ISSUE THREAD

**Issue by MyuziQ** [tobykurien/WebApps#136]
After saving a website through the WebApps client, the website icon displays in a low resolution. Is there a way to fixing this? (i.e. Reddit's icon is clearer than the other 3)

![webappsexample](https://user-images.githubusercontent.com/49368010/55684671-6ee6b000-593d-11e9-881a-99c510322ccf.png)

**Comment by trymeouteh** [comment]
Please add a feature to add our own png icons which can also be used as the shortcut icon.

**Comment by tobykurien** [comment]
This is site dependent, some sites like facebook do provide higher res icons, but need some CDNs or 3rd party to be unblocked.

**Comment by ams-123** [comment]
This is the only issue with webapps - the low resolution icons.

**Comment by ltGuillaume** [comment]
About the neede CDN, I'm not sure whether this is the case. I have my own site, with a favicon file that includes multiple resolutions, but WebApps still chooses the smallest somehow.
