### ISSUE TITLE
translate.google.com Does Not Work

### ISSUE THREAD

**Issue by trymeouteh** [tobykurien/WebApps#138]
When I try to add translate.google.com I get this error message...

https://www.google.com/sorry/index?continue=https://translate.google.com/$q=EgS53sqFGNmY0UFlhkA8aeDS9KHTKOZ8GBx3OOgY3y-rSH0U4QtMgFy

**Comment by sm4rk0** [comment]
I can reproduce this.
There's probably nothing that could be done to fix this, but I found a workaround:
1. Open google.com
2. Save the web app
3. Use the already opened google.com to search for translate
4. Open the Google Tranlate link
5. Save as a new web app
6. Delete the google.com web app (long tap)

**Comment by trymeouteh** [comment]
What you did does work but the Google Translate icon remains as the Google.com icon and when I added Google Translate webapp it renamed the Google webapp to Google Translate. I do not want a "Google Webapp" anyways so this does work out for me.

I wonder if it has something to do with the sub domains.

**Comment by tobykurien** [comment]
In general, Google web apps require special handling of with domains, etc. This is why I built a separate app for Google apps: GitHub · Where software is built - https://github.com/tobykurien/GoogleApps

**Comment by Mageek627** [comment]
Hello, following the deprecation of GoogleApps, shouldn't this issue be reopened ?

**Comment by tobykurien** [comment]
Agreed. FYI another workaround is to open translate.google.com in your browser, let it do it's redirects, then share the resulting url back to WebApps, and it then works.

**Comment by tobykurien** [comment]
I tried adding translate.google.com on WebApps v4.1 and it worked as expected. Closing this issue.
