### ISSUE TITLE
feature request: edit webapps

### ISSUE THREAD

**Issue by rigid** [tobykurien/WebApps#14]
it would be nice, if webapp entries could be edited after adding them

**Comment by tobykurien** [comment]
You can edit them by re-saving.

**Comment by rigid** [comment]
ok, maybe open the app on longpress-entry -> "Edit app" and display toast "Make changes and save webapp" would be user friendly UI sugar? not sure. please close if you don't think so.

**Comment by tobykurien** [comment]
Yes I think that's a good idea. The popup would then list all the currently unblocked domains, giving you a chance to block them again.

**Comment by sm4rk0** [comment]
How about editing the URL, too? Without the possibility to edit the host part of the URL, of course, as that wouldn't be safe.

**Comment by tobykurien** [comment]
This is currently possible, by navigating to the page you want and then re-saving the webapp.
