### ISSUE TITLE
Feature Request: Allow Multiple Domains Within WebApps

### ISSUE THREAD

**Issue by trymeouteh** [tobykurien/WebApps#140]
I tried to add MarketWatch as an web app and it works but to login it is not possible since the URL is a different sub domain to login and will always open in my Browser, not in WebApp. Please add a feature to allow multiple domains and sub domains within each web app.

**Comment by tobykurien** [comment]
That is unfortunately too big a change. I suggest that you save the login page as another WebApp, i.e. when it opens in a browser, share it back to WebApps, save as another web app, and login. Hopefully it then redirects you back to the other sandbox. I have tested and used this method before, e.g. for authenticating to Twitter, etc.

**Comment by virhonestum** [comment]
I would also love this feature since it seems to be impossible to log into any google service with the redirect - share back method.

**Comment by tobykurien** [comment]
For Google apps, please use GApps:

https://GitHub.com/tobykurien/googleapps

**Comment by tobykurien** [comment]
closed as duplicate, refer to #211
