### ISSUE TITLE
Certification updates not being saved

### ISSUE THREAD

**Issue by puppykickr** [tobykurien/WebApps#144]
Great app, by the way.

But when a certification change notice is displayed, there is no difference when I click on 'accept' or cancel.

The same notification will appear over and over again.

It is becoming irritating, as it seems to occur on most sites.

**Comment by tobykurien** [comment]
This hasn't been my experience, it saves the new certificate for me if I click accept. However, I have noticed with Twitter (for example), that if I use a VPN, it serves a different certificate for different regions, e.g. going via UK gets a different certificate to going from local. Thus I see the cert changed notification each time I switch between the networks. Could your situation be similar?

**Comment by puppykickr** [comment]
No, I usually do not use a VPN.
Anytime I see the certification page, it will pop up repeatedly.

I will attempt to make a screen recording and leave a link to it.

**Comment by tobykurien** [comment]
Ok, also swipe left/right when you see the pop-up and compare the certificates. Perhaps the site is switching between multiple certificates for different subdomains.

On June 28, 2019 7:12:47 AM GMT+02:00, puppykickr <notifications@github.com> wrote:
>No, I usually do not use a VPN.
>Anytime I see the certification page, it will pop up repeatedly.
>
>I will attempt to make a screen recording and leave a link to it.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/tobykurien/WebApps/issues/144#issuecomment-506602948

-- 
tobykurien.com | @tobykurien

**Comment by Friptick** [comment]
This started happening recently on Agoda.com and Booking.com, which are owned by the same company BTW. They seem to be doing something strange with their certificates.  On almost every page view it asks for the update, always twice in a row but apparently for the same certificate. Would be great if you could investigate.

**Comment by Friptick** [comment]
Also happening on HappyCow.net.

**Comment by puppykickr** [comment]
It is even happening on DuckDuckGo, and this is one of the 'pre-loaded' web apps.

It is happening quite often.

**Comment by Friptick** [comment]
Perhaps it would be simplest just to add a global setting "Accept all certificates from this domain" ? In terms of security that is hardly worse than the alternative of reflexively clicking "Accept" to everything that pops up. This is otherwise a great app BTW, thanks so much.

**Comment by tobykurien** [comment]
Even simpler might be to only show the alert if the issuer changes? That would still detect MITM but ignore cert updates, sub-domain and wildcard certs, etc.

**Comment by Friptick** [comment]
Thanks for this, looking forward to trying it! Any ETA on a new version of the F-Droid package?
