### ISSUE TITLE
Low-Res icons in homescreen shortcuts

### ISSUE THREAD

**Issue by Alexanderlll** [tobykurien/WebApps#146]
sometimes happens, not always, but happens, thanks a lot for your time

**Comment by Friptick** [comment]
Duplicate of #136

**Comment by Alexanderlll** [comment]
may i close this issue? i'm new here so :D

**Comment by Friptick** [comment]
No problem, I'm just trying to help the maintainer. Maybe close it and give a thumbs-up vote to issue #136. :)

**Comment by Alexanderlll** [comment]
all right!
