### ISSUE TITLE
Twitter keeps logging me out

### ISSUE THREAD

**Issue by edent** [tobykurien/WebApps#149]
Brilliant little app. Every few days I have to log back in to Twitter. Facebooks doesn't have this problem.

Sometimes I'll be in the middle of reading Twitter, and then suddenly I'm logged out. I'm not blocking 3rd party requests.

Any idea how I can fix it?

**Comment by tobykurien** [comment]
It happened intermittently to me. I am not sure what is causing it, could be the blocking of 3rd party cookies, not sure.

**Comment by edent** [comment]
Oh well, at least it isn't just me!

**Comment by tobykurien** [comment]
That said, it has been working fine for me for several weeks, ever since I deleted my twitter app and re-added it after the new twitter UI refresh. YMMV.

**Comment by ElBarto90** [comment]
Having the same issues. Also even when it's not logging me out, it doesn't remember the theming settings. I have to set twitter to use dark theme again every time I open the web app.

**Comment by tobykurien** [comment]
Please see #152
