### ISSUE TITLE
f-droid version of app doesn't work

### ISSUE THREAD

**Issue by tobykurien** [tobykurien/WebApps#15]
- null entries in default list
- crashes
- doesn't save

**Comment by tobykurien** [comment]
Should be fixed when https://github.com/tobykurien/WebApps/releases/tag/v1.3.2 becomes available on f-droid

**Comment by krt16s** [comment]
You haven't updated versionName and versionCode in the AndroidManifest.xml

**Comment by tobykurien** [comment]
Aaah ok, thanks!
