### ISSUE TITLE
Logging out of websites

### ISSUE THREAD

**Issue by PrabuddhaKumar** [tobykurien/WebApps#152]
The idea and implementation of the app is really great. I am trying to use this as a replacement for instagram, reddit, linkedin, twitter and facebook android applications. 

The only thing stopping me from completely making the switch is the fact that I am being logged out extremely frequently from these apps. LinkedIn and twitter are especially aggressive with logging out.

Could you look into this?

**Comment by tobykurien** [comment]
I am using it for Twitter and have not been logged out for months. I wonder if the issue is elsewhere. Could you provide some details? What phone model, what webview version?

**Comment by PrabuddhaKumar** [comment]
I am using a Pixel 2, running Android 10, Webview 77.0.3865.92.

**Comment by logic** [comment]
Fwiw, this has been happening pretty constantly to me for multiple apps (Twitter and Mastodon are the most glaring examples; twitter seems to losing client-side theme settings from run to run as well). In some cases, simply logging in again doesn't work, I end up having to delete the webapp and re-add it from scratch.

Galaxy S7, Android 9 (LineageOS plus microg), Android System WebView 76.0.3809.111

**Comment by sm4rk0** [comment]
This issue was already discussed in #98

**Comment by jeroen7s** [comment]
@sm4rk0 that's a different issue, this is about sites randomly logging out (cookies cleared??) when normally they shouldn't. 
That ticket is about storing credentials like in browser based password managers.

**Comment by jeroen7s** [comment]
I have the same issue, most prominently on Youtube, keeps randomly logging me out, but happens on twitter as well.

**Comment by jeroen7s** [comment]
when I open the youtube webapp from home shortcut, I see a brief glimps of logged in logged in youtube, only for it to refresh after half a second being logged out.

**Comment by tobykurien** [comment]
I agree that this is not the same as #98. I managed to replicate this issue in Firefox actually - if I keep cookies, but delete everything else (cache, offline data e.g. localStorage) then Twitter logs me out (most other sites stay logged in). I suspect Twitter are now requiring local storage because more and more people are deleting cookies or blocking 3rd party cookies. I view local storage and cache the same as cookies - they store unique data and allow you to be tracked. So it seems I will not be able to "fix" this.

**Comment by jeroen7s** [comment]
So youtube does the same thing? Also use localstorage? Or is it because the login domain (account.google.com, which sets the cookie) is a different domain than the website?

**Comment by tobykurien** [comment]
Yea youtube might be related to the login domain being a 3rd party domain. I should just be clear that my conclusion above is just a theory, I am not 100% sure of it, just based on the fact that Twitter got logged out even though cookies were retained in Firefox, but Mastodon stayed logged in.

**Comment by jeroen7s** [comment]
Just tested this for youtube, deleting everything but cookies in FF beta on android does not log me out like twitter does, so this does seem related to the "3rd party" domain cookie YT uses.

**Comment by jeroen7s** [comment]
Maybe implement an "Equivalent Domain" list for domains that belong together, like messenger.com and facebook.com ; youtube.com and google.com
Bitwarden keeps a list like this for autofill in it's password manager: 
https://github.com/bitwarden/server/blob/master/src/Core/Utilities/StaticStore.cs
