### ISSUE TITLE
Form submission with POST not supported

### ISSUE THREAD

**Issue by keganlance** [tobykurien/WebApps#159]
I'm having a website which submits a form using POST to improve privacy. This opens a different website. Similar to how startpage.com uses POST requests.

However, when submitting a POST form I get a blank page with "[blocked]".

Keep in mind the submitted form url is not the one from the webapp. It's supposed to open an external website similar to a GET request. Tho maybe this is not possible in android?

**Comment by tobykurien** [comment]
A form POST to an external URL cannot be opened in an external browser (the form data will be lost), only GET requests are supported. Even if the POST was to another sandbox, that would not work.
