### ISSUE TITLE
Application rendering error

### ISSUE THREAD

**Issue by leela52452** [tobykurien/WebApps#160]
URL https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Crash_reporting

can you please look into it

**Comment by tobykurien** [comment]
What is the actual issue?

**Comment by leela52452** [comment]
webapps 2.23

it just shows

![Screenshot_2019-10-24-16-13-51](https://user-images.githubusercontent.com/52065244/67478259-35606280-f64b-11e9-8eac-25ff992fcbc8.png)

**Comment by tobykurien** [comment]
It renders fin on my device. Try updatin your System Webview.

**Comment by leela52452** [comment]
i am struck with 5.1
can i upgrade webview ?

**Comment by tobykurien** [comment]
Probably not, sorry. I have an Android 6 tablet with the same issue. The only option seems to be to buy a new device. Anyway I am closing this issue as it not related to WebApps.

**Comment by leela52452** [comment]
i replaced with android system webview, however it still does not work.
>Probably not, sorry. I have an Android 6 tablet with the same issue. The only option seems to be to buy a new device
you are absolutely right
