### ISSUE TITLE
Feature request : ad blocker

### ISSUE THREAD

**Issue by ksdrummer** [tobykurien/WebApps#161]
Hi ! Thank you very much for the amazing work on this app !
It would be so great have an ad blocker. I don't know how hard it is to implement ...
Anyway, thanks again !

**Comment by ildar** [comment]
I am sorry to intrude as I'm not a developer.
This app already restricts data coming from the internet by filtering
domains (branching arrow). You just need to exclude domains bringing ads.

**Comment by tobykurien** [comment]
Agree with @ildar ads are automatically blocked unless you unblock them.
