### ISSUE TITLE
(feature request) Ability To Disable 'Certificate' Notification

### ISSUE THREAD

**Issue by puppykickr** [tobykurien/WebApps#163]
The 'Certificate' issue is happening again.

This app works great aside from endlessly having to accept cerificate after certificate after certificate after certif............

Good God, couldn't there just be a setting to allow those of us that can't seem to get the app to save an accepted certificate to just turn that process off altogether?

Would this really be any less secure than just blindly tapping 'accept' over and over again?

**Comment by tobykurien** [comment]
Could you please provide some details, like which site and maybe a screenshot or what is different for the old vs new?

Some sites are jst incompatible with high security, e.g. Google's apps that rely on redirects and third party cookies. If the solution is to reduce security, maybe just use a normal browser for those sites?

**Comment by Friptick** [comment]
Can confirm. Getting it again with Agoda.com, exactly as described previously.

About security, my use-case for this app is perhaps different from what you designed it for. I want (1) homescreen icons to web apps where (2, bonus) they are sandboxed away from general browsing. This does _not_ mean that the sites are untrusted, it usually means the opposite! It is the general browsing i treat as untrusted, to be done in locked-down browser (now Firefox Klar AKA Focus), where it is therefore impossible to make persistent homescreen bookmarks.

Is this workflow misguided?

**Comment by tobykurien** [comment]
Not misguided, no. I created the fork https://github.com/tobykurien/webmediashare for such cases, where I don't need the crazy security. You clould try using that.

**Comment by puppykickr** [comment]
And I as well have a different agenda for using WebApps.

I am sick of logging in on countless websites over and over again.

My chosen browser, Lightning, is very secure, but due to my security
settings it remembers nothing as far as login credentials.

Also, it is not Auto-Fill compatible, so using Bitwarden or the like is not
a viable option.

WebApps solves this all for me by allowing a large amount of security while
allowing me to stay logged in on lots of sites.

The only issue is with these certificates that don't get saved for some
reason.

As the only remedy seems to be mindlessly checking 'Accept' repeatedly.

As this is a less than secure method, I just thought that having the option
to avoid the 'certificate situation' all together would be fine for those
of us in my situation.

Thank you for all the work on this app, as it has been great for why I use
it, except for this one issue.

Grant Ryan Swan
  (puppykicker)

**Comment by puppykickr** [comment]
Wow!

I am so sorry that I had no idea that you were behind Web Media Share!

I guess I wasn't paying enough attention.

This is an app I played around qith a bit before, however I had relegated it to my 'media' device a while back.

It looks like it deserves a place on my daily device as well.

I have entered some sites that I had issues with on WebApps, and it appears to be working.

I appologize for sounding exasperated in my original post, but I kind of was, hahaha.

**Comment by puppykickr** [comment]
@Friptick 

I took the liberty of checking the site you mentioned, and it loads up flawlessly on WebMediaShare.

It appears that this app is the quick and simple solution to the problem.

**Comment by Friptick** [comment]
@puppykickr It normally loads up well on WebApps as well, the new issue seems random! But yep, I have now switched it to WebMediaShare.

@tobykurien Some suggestions, because I think your work deserves to be more popular. Firstly, there are definitely two different rationales at work here. I see web-app homescreen-ing, even with access to device APIs, as a kind of attainable utopia. After all, web apps are by definition open-source and also much more lightweight than native apps. But I get that others are more concerned by sandboxing the APIs, and that app-level resource-sharing means you need a separate app (this one) for that use case. But how about merging the GApps container app with WebMediaShare and then giving it optional access to all system APIs? In particular _location_! (An open issue on the tracker.) So annoying not to have location on some sites, but I will continue to put up with it in order not to install black-box bloatware! :) And you might then rename the result to something really obvious, such as WebAppsLite, since WebMediaShare seems a bit opaque. Anyway, just some suggestions. Thanks so much for your work on these apps, it is appreciated.

**Comment by tobykurien** [comment]
Thanks for the comments and feedback everyone! Believe it or not, I too get fustrated when certificate issues pop up, or I get logged out of sites randomly. I definitely plan on expanding WebMediaShare a bit - it was pimarily written to handle 'hostile' sites like live streaming sports sites, but I now also use it for sites that don't work well on WebApps.

**Comment by puppykickr** [comment]
You wanted some specific sites, so I have some for you-  especially as the issue has gotten worse lately.

Youtube
Gab
Best Gore

Youtube works fine on Web Media Share
Gab works fine on it as well, but Gab Trends will not log in.
Best Gore works ok on Web Media Share, but I have to use a captcha to log in.

Disqus will not log in on Web Media Share

I am still in the process of setting up Web Media Share as I have with Web Apps, to see what works and what does not.

**Comment by tobykurien** [comment]
I have tested YouTube and Agoda and I am not seeing the issue. Do I need to be logged in to see the issue? Some screenshots or copy & paste of old vs new certs would help me figure out what's going on.

**Comment by Friptick** [comment]
@tobykurien For YouTube, I use it in WebMediaShare without cert problems, perhaps that is a clue. For Agoda, yes, logged in. No recent experience as I had given up and gone back to the native app, but I just gave it a spin in WebApps and there were no cert issues. But this problem did disappear in the past for a while before reappearing, so I will try using it again and let you know. For now consider Agoda resolved.

**Comment by tobykurien** [comment]
Feature has been added to v3.00
