### ISSUE TITLE
Show app name/colour in app switcher

### ISSUE THREAD

**Issue by Friptick** [tobykurien/WebApps#165]
Progressive Web Apps (PWAs) are theoretically the holy grail. Already many are good enough to replace native apps.

Of course, PWA is partly just a marketing term meaning "modern app-like website". But PWAs do have some specific qualities requiring support in a browser:
* TLS (easy)
* a manifest, to tell the OS how to implement the icon
* a service worker, typically used to cache the "app shell", or static interface, for offline use

What's the current situation on support for these?

**Comment by tobykurien** [comment]
They already work within WebApps, except that serviceworkers will not continue to run in the background if you close the app. I logged a separate issue for that #107

**Comment by Friptick** [comment]
Thanks @tobykurien. There is at least an issue with the app-screen chrome. When cycling thru apps (stock Android 8), the title bar for added-to-home WebApps containers only ever shows just "WebApps". Whereas when the same sites have been added-to-home using the Samsung browser or Firefox, the app title bars show "Twitter", "Google" etc. Not a show-stopper but certainly a bit of a drawback when switching thru a bunch of apps and all have the same name. Difficult to fix?

**Comment by tobykurien** [comment]
That might be difficult, yes. I believe the browsers generate an APK for each PWA and install each as a separate app. This might be something WebApps could try to do as well, will look into it.

**Comment by tobykurien** [comment]
Note to myself: this is possible using the "document-centric" API for the Recents screen: https://developer.android.com/guide/components/activities/recents

**Comment by Friptick** [comment]
Confirming belatedly that this works great.
