### ISSUE TITLE
Can't login in Pixiv.net. It tries to open in other browser.

### ISSUE THREAD

**Issue by LukasThyWalls** [tobykurien/WebApps#170]
In WebApps, when you tap "Login" in "Pixiv.net", i tries to open in other browser.
Inspecting in other browser, it's opening "accounts.pixiv.net".

I tried to open directly "accounts.pixiv.net", but when you enter you credentials and tap the login button, it tries again to open other browser (for sure, is returning to "pixiv.net").

**Comment by Brli** [comment]
When open new webapp, you need to enable the "temporary enable redirect" option

**Comment by LukasThyWalls** [comment]
Thank you. I was testing this feature since a week or so (since i see it) and i have some issues with not maintaining the logging at the beginning, but now i'm using it during a few days and it works normally.

Closing and Thanks.
