### ISSUE TITLE
Enable native backups

### ISSUE THREAD

**Issue by RichyHBM** [tobykurien/WebApps#171]
This will ensure you don't accidentally lose any created app lists, and would at the simplest form be a case of seeing `android:allowBackup` to true in the manifest

**Comment by tobykurien** [comment]
My reason for not allowing native backups is for this threat model: my phone is confiscated at a border and I am compelled to unlock it (this has happened to me). They can then do an adb backup of my phone.

**Comment by RichyHBM** [comment]
I dont think allowBackup stops adb backups though, I think allowBackups is only wether android backsup to the cloud (google)

**Comment by tobykurien** [comment]
Not according to this: https://stackoverflow.com/questions/12648373/what-is-androidallowbackup
