### ISSUE TITLE
Minimizing the app + clicking on WebApps icon = return to home menu

### ISSUE THREAD

**Issue by WPFilmmaker** [tobykurien/WebApps#180]
I don't know if this intended but it is quite frustrating.

**How to reproduce:**
1 Open WebApps and open one of the saved apps

2 Minimize it with your Android button (mine is a circle)

3 Press again on WebApps icon on

4 Instead of showing the app where you left, WebApps shows the 'home menu' where you can select all your saved apps.

version 3.10 from f-droid.

**Comment by ildar** [comment]
That's because it's multi-app.
Use Homescreen Shortcut

**Comment by WPFilmmaker** [comment]
worked thanks!
