### ISSUE TITLE
Opening new sandbox of the same site does not forget previous data

### ISSUE THREAD

**Issue by Tiberion000** [tobykurien/WebApps#181]
When I open a website like twitter.com and save it as a webapp, the app won't create a separate sandbox if i try to make another webapp with a different name.

**Comment by tobykurien** [comment]
It will, if you open twitter as a new site and tick "open in a new sandbox", then save it.

**Comment by Tiberion000** [comment]
Apologies for the misinformation. I was trying it on mail.tutanota.com and assumed it was the case for other sites as well.
