### ISSUE TITLE
Improvements to UA selection

### ISSUE THREAD

**Issue by WPFilmmaker** [tobykurien/WebApps#182]
Right now you can select user agent however it is quite confusing imho.

This is what an usual User Agent looks like:

**Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36**

Let's have a look at the list of UAs and in brackets my comments:

Default  (what is that? It has no specifications)
Custom (clicking on it I would expect to being able to insert UA manually but nothing happens)
Desktop (it it chrome desktop?which version? IMHO it would be nice having with chrome and firefox)
Android 4.4.2 Chrome (why 4.4.2 in particular?Is there any reasons?)
Tablet Android 4.1.1 (same as above)
Phone Android 4.1.1 (same as above, is it just for a larger screen?)
Tablet Android 2.2 (this version is from 2010Is there any reasons?!)
Phone Android 2.2 (same as above)
Iphone safari (which version?)
ipad safari (which version?)

It would be useful having it reworked to make it more clear, if I have an issue on a website I should know what UA is causing the issue, having a general 'default' or 'desktop' does not help much.

https://github.com/sereneblue/chameleon/issues provides a very good presets of UAs so you could use that.

Please don't take my feedbacks as criticism but as a way to improve this useful app ^^

**Comment by tobykurien** [comment]
Those User Agents were chosen by me, specifically based on how they affected Google News and other Google sites, back in the days of Android 4, back when WebApps  fork of GoogleApps (https://github.com/tobykurien/googleapps) didn't exist. So it's legacy. Is changing user agents still useful? I've not had to do that in years.

**Comment by WPFilmmaker** [comment]
@tobykurien thank you for the reply, I think they can be useful as some site require desktop view or for whatever glitch one version does not work properly and you have to switch. Also spoofing user agent is quite nice privacy wise, so I would not remove, what I suggest is to improve it as I mentioned above, and maybe remove some unused options (Like merge iphone and ipad, and maybe tablet and android phone 2.2?).

Having such old UAs I doubt it still helpful today, as now many site warn you to update if you don't have a new browser.

**Comment by zayuim** [comment]
@tobykurien @WPFilmmaker 
I got some new ones together and made a merge request.

**Comment by WPFilmmaker** [comment]
@zayuim it seems that webmedia share has the same issue, would you be kind enough to update user agents there too? so that @tobykurien can merge the request and in next release we have updated user agent there too?

**Comment by tobykurien** [comment]
No need, I can pull them from here. Added an issue to remind myself.
