### ISSUE TITLE
InvocationTargetException

### ISSUE THREAD

**Issue by JonnyTech** [tobykurien/WebApps#189]
I have just upgraded to v3.30 from F-Droid on Android 10 and the app no longer works. The previous versions were working correctly. If I try to open a webapp then an error message toast about importing cookies and InvocationTargetException is displayed and the link does not open. Have tried clearing data,  cache, and uninstalling then reinstalling too. No change. Also when going to the info page then clicking the source code link to try to get here then that also fails with the InvocationTargetException error. Here are screenshots with error messages displayed:

![Screenshot_20200527-091841](https://user-images.githubusercontent.com/3584732/82999259-a82a2580-a000-11ea-9bf4-42dc22a55b5c.png)

![Screenshot_20200527-092106](https://user-images.githubusercontent.com/3584732/82999287-b1b38d80-a000-11ea-9182-9c6e3fb1d0bb.png)

**Comment by tobykurien** [comment]
I am running v3.30 from F-Droid on Android 10, and I don't get that error. Could it be something to do with the system webview?

**Comment by JonnyTech** [comment]
Good call! I reinstalled the system webview and that fixed it. Strange that no other apps showed a problem. Many thanks.
