### ISSUE TITLE
Feature request: edit URLs of saved Webapps

### ISSUE THREAD

**Issue by Rudd-O** [tobykurien/WebApps#190]
Hello there!  It is currently not possible to edit the URLs of Webapps saved in the sandbox.  Can we get that feature?  Thanks.

**Comment by tobykurien** [comment]
you can re-save the webapp from whichever screen you want to be the default

**Comment by Rudd-O** [comment]
That doesn't work for the use case I'm thinking of.  Some webapps (I'm thinking The Old Reader, but many others too) have a permanent / temporary redirect to a specific URL that has some hash identifier in the URL which is only applicable to the specific session / time you are browsing.  This is why editing the URL is important.

I've uninstalled the app and I will not be recommending it anymore, so feel free to disregard this bug request.  Have a good day.
