### ISSUE TITLE
Register web apps to handle external links

### ISSUE THREAD

**Issue by austinried** [tobykurien/WebApps#195]
Just trying this application out and liking it so far, but I would really like it to be able to handle links from other apps.  For example, I've set up a web app sandbox for Twitter, and when I click on a twitter link (either from another web app or from another application) I'd like to be able to specify that WebApps, specifically my Twitter web app, is the handler for that so it opens in the sandbox.

**Comment by tobykurien** [comment]
If you click from inside a webapp, it does open the sandbox for the site you clicked on. To register as a handler it needs to be be hardcoded in the app manifest, so the only option is to handle all https links. A previous version of WebApps did this, but every link is a constant fight between WebApps and the default browser, so I removed it. From the browser, you can share the site to WebApps to open it's sandbox.

**Comment by austinried** [comment]
Ah, sounds like it's not possible to generate/modify those at runtime then? That is unfortunate.
