### ISSUE TITLE
Feature request: View images based on device's screen resoultion

### ISSUE THREAD

**Issue by CalibSerrano** [tobykurien/WebApps#201]
It appers that images shows based on its size and not fit to screen. Large images looks like zoom in and cannot be zoom out because WebApps does not support pinch zoom gesture.

**Comment by tobykurien** [comment]
This may be site specific, one site I visit requires 3rd party JavaScript to resize the image correctly, otherwise it is zoomed in even on a desktop. Try unblocking 3rd party requests and see if that fixes the images.
