### ISSUE TITLE
Share in chrome browser cannot share to webaps

### ISSUE THREAD

**Issue by gilluc** [tobykurien/WebApps#202]
Webapps link is present in the share list but i cannot share to twitter or linkedin web apps as it is possible with official apps... 

It is a big issue for me.

**Comment by tobykurien** [comment]
I tested this on my phone and it works as expected. I browsed to a site in Chrome that also has a sandbox in WebApps, I then went into a specific page, shared that to WebApps, and WebApps opened that specific page it in the sandbox. Can you maybe try on another device?

**Comment by tobykurien** [comment]
Individual webapps won't appear in the share menu, but you can share to WebApps and it will open the link in the correct webapp.
