### ISSUE TITLE
"Recommended WebApps" ideas

### ISSUE THREAD

**Issue by BasilTomato** [tobykurien/WebApps#210]
Some ideas for the "Recommended WebApps" section of the wiki:

Following web sites are working quite well with WebApps:
- [Cryptee](https://github.com/cryptee/web-client): notes editor and picture manager with end-to-end encryption
- [MiniFlux](https://github.com/miniflux/miniflux): minimalist feed reader

Furthermore some PWA sites as possible web app sources:
- https://appsco.pe/
- https://pwa-directory.appspot.com/

**Comment by tobykurien** [comment]
Feel free to edit the page yourself, it's open for editing to everyone.

**Comment by BasilTomato** [comment]
OK, thank you!
