### ISSUE TITLE
Can't login to Gmail

### ISSUE THREAD

**Issue by Sepero** [tobykurien/WebApps#211]
To login to Gmail, there is a login redirect to Google.com. Because Webapps does not allow the (temporary) option of allowing other domains, logging into Gmail is currently not possible. Webapps would be an appropriate use for all Google based services.

**Comment by tobykurien** [comment]
You need to save google.com as another sandboxed app, so that the redirect will open that sandbox, log you in, and re-direct you back. There may be multiple redirects though, making this more difficult, which is why [GoogleApps](https://github.com/tobykurien/GoogleApps) exists.

**Comment by Sepero** [comment]
@tobykurien
Thanks for the tips! I've tried Gapps before, but I stopped using it because I don't use most of Google services, and I found it to be redundant with Webapps. And we can use Webapps with almost any site (not just Google).

A problem I have discovered with Gapps, is that it doesn't have a method for multiple accounts. For example, I have multiple Gmail accounts, but Gapps only allows for login of a single account. Webapps is far better designed to handle multiple accounts.

I tried the trick you stated about having google in a separate sandbox, and it sort of worked, but then didn't. :(

For gmail.com, it redirects to accounts.google.com. So I created both of those, and it seemed to go, but after logging into accounts.google.com, it redirected me to the local url accounts.google.co.th

I tried to make an accounts.google.co.th sandbox, but it's impossible, because if you go directly to that address, it immediately redirects back to accounts.google.com. In the end, I failed again. No dice. 

So perhaps I can change this into a feature request for Webapps? Enable an explicit option for sandboxes to change domains. :)

Anyways, I really appreciate your help and insight into this problem. Webapps developers are awesome!

**Comment by Sepero** [comment]
I promise you that I don't want to use Google.Haha. But the reason I have multiple accounts is precisely -because- I distrust Google (as should we all). By keeping our information separated, we prevent Google from building a complete database on us. So I have one account for YouTube, and another account for Maps, etc, etc.

But the common thing is that, sometimes I need to login to the Gmail of these different accounts. Currently my solution is Private Browsing tabs, but Google always gives me a hassle because "we see you never logged in from this browser before".

If it were possible to change domains in a sandbox, I could avoid that problem, and still save the necessary cookies.

We're all adults here, and we can be responsible. I don't have much, but perhaps you would accept a $100 donation to add this feature into Webapps.

I appreciate your consideration here. The work you're doing is valuable to us all.

**Comment by tobykurien** [comment]
I don't accept payments for features currently (I have a full time job already). I do think the ability to allow redirects temporarily during login is very useful, so I will look into it, but no ETA (esp. since it doesn't currently affect me).

**Comment by Sepero** [comment]
Understood. Hotmail and a couple other sites also give me the "domain bounce around" annoyance too, so I'll look forward to this feature whenever you're able to get around to it. If I could, I'd still be happy to PayPal you the money now. I appreciate your work, and l'll include my email in the next comment. Contact me there with your info.

**Comment by Sepero** [comment]
cowpie2000@hotmail.com

**Comment by tobykurien** [comment]
Please test with v4.0, and tick the 'Temporarily allow redirects' option.

**Comment by Sepero** [comment]
It works! But there appears to be a bug I've discovered. I tried doing random Google searches with it. Sometimes a Google link is able to (redirect?) bounce me out of WebApps, and over to Chrome, and begin loading a webpage in Chrome.

In spite of that, the domain changing seems to work great, and I was able to log into Hotmail flawlessly. 😊👍
