### ISSUE TITLE
Unsupport HTTP

### ISSUE THREAD

**Issue by black-cerberon** [tobykurien/WebApps#214]
Cant connect to basic HTTP servers (like router admin panel).

**Comment by tobykurien** [comment]
This is by design, you can use a regular browser and bookmark for insecure sites.

**Comment by danielquinn** [comment]
For what it's worth, I was really disappointed by this, as I was explicitly looking for a way to have launchable "apps" on my phone that just go to internal services in my home like my file server, router, Paperless install, etc.  As all of these services are private (not on the public web), they don't have a certificate, so this app didn't work for me.

If the limitation is artificially imposed, I'd suggest that there's a good reason to lift it.

**Comment by tobykurien** [comment]
For that, you can use this app (which is a fork of WebApps):

https://github.com/tobykurien/webmediashare



On 23 March 2021 22:31:54 GMT+02:00, Daniel Quinn ***@***.***> wrote:
>For what it's worth, I was really disappointed by this, as I was
>explicitly looking for a way to have launchable "apps" on my phone that
>just go to internal services in my home like my file server, router,
>Paperless install, etc.  As all of these services are private (not on
>the public web), they don't have a certificate, so this app didn't work
>for me.
>
>If the limitation is artificially imposed, I'd suggest that there's a
>good reason to lift it.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/tobykurien/WebApps/issues/214#issuecomment-805231217

-- 
tobykurien.com | @tobykurien

**Comment by danielquinn** [comment]
That's excellent!  Thank you!
