### ISSUE TITLE
google groups new topic hangs

### ISSUE THREAD

**Issue by nutpantz** [tobykurien/WebApps#22]
I've been trying this app recently and when I tried to post a new topic in google groups it hung at loading the Window to create the post.
It could be my setup but maybe a bug if anyone else can reproduce.

**Comment by tobykurien** [comment]
@nutpantz did you unblock the required 3rd party domains e.g. gstatic.com? Also, for Google-related webapps, I highly recommend using https://github.com/tobykurien/GoogleApps instead

**Comment by nutpantz** [comment]
Yes my bad, it was g static being blocked.but I love gapp browser,I  Will switch to that for google sites. Thank you
