### ISSUE TITLE
Feature request: save content by long press

### ISSUE THREAD

**Issue by Brli** [tobykurien/WebApps#225]
Needs to download files from page, like pic or txt.

**Comment by pokegamer5547** [comment]
Is this going to be implemented soon?

**Comment by Brli** [comment]
Hi, just dropped by to say it doesn't work (at least on Android11)

The commit only introduce a "Share the url" dialog instead of save to phone storage.

the url might be forbidden for no cookie or enough auth.

maybe you should introduce the permission to write to storage and fetch the cached files (multimedia, documents etc.) directly?
