### ISSUE TITLE
Can't use Twitter

### ISSUE THREAD

**Issue by pokegamer5547** [tobykurien/WebApps#226]
I can't login in Twitter. This is how it's happening always in this app.
I try to login Twitter account and after entering my username and password (and  2fa) , it's just redirects me back to login page. I have ticked "allow temporary redirects" and unticked all trackers to make sure it will login but it still doesn't. And after closing the site the Twitter just don't add in webapps  list at all. It just shows "mobile. Twitter. Com" but it doesn't add to it's list even if I try multiple times. Clearing data doesn't help either.
My pinterest is working fine in this app so idk what's wrong with Twitter.

**Comment by tobykurien** [comment]
Yup, confirmed, Twitter is broken.
