### ISSUE TITLE
Location access per web-app?

### ISSUE THREAD

**Issue by atom-smasher** [tobykurien/WebApps#229]
Playing around with a popular mapping web-app it works well, but it seems like enabling location for WebApps is handled by the OS, and applies globally to all web-apps handled by WebApps.

Would it be possible for WebApps to handle location access on a per-app basis?

Thanks.

**Comment by atom-smasher** [comment]
Seems like it already does this, but the documentation isn't clear. If the behaviour is already limiting location access to specific web-apps, and can also be "reset" (aka revoked or allowed) or a per-app basis, then I'm happy for this issue to be closed. Thanks.

**Comment by tobykurien** [comment]
Yes you can use the `Reset` menu item to reset the location permission.
