### ISSUE TITLE
Support localStorage and CORS?

### ISSUE THREAD

**Issue by untitaker** [tobykurien/WebApps#27]
I am trying to use apps based on [remotestorage](https://remotestorage.io/) (such as http://myfavoritedrinks.5apps.com/), but something in the authentication process fails. I suspect that either CORS requests or localStorage is blocked/unsupported by WebApps. The same apps work fine in the Android stock browser.

It'd be nice if WebApps provided a way to view console logs so I can debug this problem. For example, the stock browser sends everything from `console.log` to logcat.

**Comment by tobykurien** [comment]
Thanks for logging the issue. Which version of the app are you using? I recently enabled DOM storage (v2+) in WebApps (the version on Google Play).

**Comment by untitaker** [comment]
I see, I am using the version from FDroid. Will report back when the new version is available there.

On 8 September 2015 16:19:13 CEST, Toby Kurien <notifications@github.com> wrote:
>Thanks for logging the issue. Which version of the app are you using? I
>recently enabled DOM storage (v2+) in WebApps (the version on Google
>Play).
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/tobykurien/WebApps/issues/27#issuecomment-138575262

-- 
Sent from my phone. Please excuse my brevity.

**Comment by tobykurien** [comment]
Unfortunately I'm having trouble getting the update into FDroid (see #20). So it might be a while (if at all).

**Comment by tobykurien** [comment]
Closing, please re-open if still an issue.
