### ISSUE TITLE
Crosswalk vs. native WebView

### ISSUE THREAD

**Issue by Buggaboo** [tobykurien/WebApps#32]
Hi,

Have you considered using [CrossWalk](https://crosswalk-project.org/documentation/embedding_crosswalk.html) instead?

**Comment by tobykurien** [comment]
Embedding CrossWalk will bloat the app massively. Also, I'd have to keep updating the app everytime CrossWalk is updated. In Lollipop+, the system WebView is updated from Google Play.

**Comment by Buggaboo** [comment]
Good point.
