### ISSUE TITLE
Action bar display option when launched from shortcut

### ISSUE THREAD

**Issue by Llamatron2112** [tobykurien/WebApps#33]
It could be usefull to have the ability to hide totally the action bar when the webapp is launched through a shortcut so the webapp displays just like any app on the screen.

**Comment by tobykurien** [comment]
I like this idea. I can change "autohide actionbar" to hide on launch even when launched from webapps list, and only appear on scroll up.

**Comment by Llamatron2112** [comment]
I was really thinking about hiding it totally when launched like an app, chrome does that on some "add to home page" (or however it's called in english) links, not all though and I didn't understand in which case it does.

The reasons for such a choice would be to avoid having the colors clash between the actionbar and the page, screen estate, and a more "integrated" feeling.

**Comment by tobykurien** [comment]
Then how would you access the stop/refresh action? I often need that when connections time out or get reset. I can imagine that once you've saved a webapp, you probably won't need access to the other actions like font size, 3rd party, etc.

With regards to the actionbar colour, see #34

**Comment by Llamatron2112** [comment]
Ha I never had to use stop/refresh yet, but I'm on wifi most of the time. That could be implemented with a gesture maybe, or one to show/hide the action bar.
