### ISSUE TITLE
Stuck at version 1.4 on F-Droid

### ISSUE THREAD

**Issue by foresto** [tobykurien/WebApps#41]
WebApps on F-Droid is only at version 1.4, while it's at version 2.2 on the Play Store.

It would be nice if your privacy-saving app didn't require privacy-invading Google services.  :)

**Comment by tobykurien** [comment]
@foresto totally agree with you. There was a build issue (see https://github.com/tobykurien/WebApps/issues/20) which I believe I've fixed, but F-droid's automatic builder still doesn't build the app. https://f-droid.org/wiki/page/com.tobykurien.webapps#v2.2 just says: 

```
We can't build this version: The build for this version was manually disabled. Reason: gradle build fails 
``` 

There's a mention of it in https://f-droid.org/forums/topic/place-to-report-outdated-packages/, and you could help by bumping the issue at https://f-droid.org/forums/topic/webapps-sandboxed-browser/

I would really like to update the version on F-droid, but I haven't had much luck.

**Comment by foresto** [comment]
I just added my voice to both f-droid threads. Here's hoping.

**Comment by krt16s** [comment]
Ref: https://gitlab.com/fdroid/fdroiddata/commit/baf57e63accb127e08d0b23b769d8f89a0235d44

**Comment by tobykurien** [comment]
Thanks! Do I need to tag a new release to get it updated on fdroid?

**Comment by krt16s** [comment]
It is already build -- on the last update `+com.tobykurien.webapps_8.apk com.tobykurien.webapps 2016-03-28` -- but only uses that have checked to be notified of "beta"/"unstable" updates will be prompted for update.

Tagging a new release will indeed bump the version that is considered stable by fdroid, thus prompting users to update.

**Comment by foresto** [comment]
Toby, is that snapshot build suitable for everyday use, or should we wait for an official release before installing?

**Comment by tobykurien** [comment]
Please wait for an official build (hopefully later today)

On 30 March 2016 03:55:48 GMT+02:00, Forest <notifications@github.com> wrote:
>Toby, is that snapshot build suitable for everyday use, or should we
>wait for an official release before installing?
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/tobykurien/WebApps/issues/41#issuecomment-203189801

-- 
http://tobykurien.com | @tobykurien

**Comment by tobykurien** [comment]
Thanks for your help with this @foresto - I am closing this issue since there is a new build on F-droid. I plan on a stable release later today.
