### ISSUE TITLE
Option to export/import apps database

### ISSUE THREAD

**Issue by tobykurien** [tobykurien/WebApps#44]
- export the sqlite db to external file for backup/restore
- exclude cookies or encrypt with password

**Comment by wesaphzt** [comment]
Any progress with this feature? Just realized I'm going to have to manually add all my apps again :(

**Comment by ildar** [comment]
Just use normal backup tools

**Comment by tobykurien** [comment]
IF you are rooted, you can copy the database file from  `/data/data/com.tobykurien.webapps/databases/webapps4.db` (doing this from memory so it may not be exactly this) into the new device and it will work. However that's not ideal so I do plan to allow export of the db to sdcard at some point, the difficulty is to add some encryption otherwise anyone getting hold of that file has access to all your sessions.

**Comment by sm4rk0** [comment]
You can also use [adb](https://developer.android.com/studio/releases/platform-tools) from your PC (no root needed).
Connect **old** phone (with [USB debugging enabled](https://www.groovypost.com/howto/mobile/how-to-enable-usb-debugging-android-phone/)) to PC then execute:
`adb pull /data/data/com.tobykurien.webapps/databases/webapps4.db`
Disconnect **old** and connect **new** phone (with USB debugging enabled) to PC then execute:
`adb push webapps4.db /data/data/com.tobykurien.webapps/databases/webapps4.db`
Don't forget to delete the webapps4.db from your PC!

**Comment by lmrsdn** [comment]
'Permission denied' when trying adb pull using adb on PC with Xiaomi Mi8...export option would be very handy if you can add it 👍

**Comment by ChristianTacke** [comment]
> […] I do plan to allow export of the db to sdcard at some point, the difficulty is to add some encryption otherwise anyone getting hold of that file has access to all your sessions.

* Start without encryption? … and put big warning before allowsing to safe?
* Then add SAF support, then people can directly safe into some protected area.
* I haven't looked into it, but maybe the PGP tools allow direct encryption from one app to the sdcard?
