### ISSUE TITLE
Support usage of multiple accounts.

### ISSUE THREAD

**Issue by LeonTheOriginal** [tobykurien/WebApps#48]
Since multiple saved webapps use the same sandbox and share cookies (at least) for the same root domain (see #3), it is currently not possible to switch between different accounts e.g. by creating two separate bookmarks (e.g. twitter.com/user1 and twitter.com/user2). This might also affect #45.
It would be interesting if it is possible to support the usage of multiple indipendent sandboxes and/or cookies for the same domain but different accounts without the need to log out and in each time.

**Comment by tobykurien** [comment]
This is fixed with #3 although on some sites, due to local caching, a reload *may* be required.
