### ISSUE TITLE
m.facebook.com login page is launched in default browser

### ISSUE THREAD

**Issue by foresto** [tobykurien/WebApps#54]
Some time within the past few weeks, WebApps started launching my phone's default browser when I try to use my facebook webapp ( https://m.facebook.com/ ). If I allow it to launch, my default browser then opens to a facebook login page. Of course, logging in to facebook in my default browser doesn't return me to WebApps, and returning to it manually shows me logged out of facebook, so WebApps is effectively broken for facebook.

It has only happened about half of the times I've launched my facebook webapp recently. The other times worked fine.

I tried deleting and re-creating my facebook webapp, but that hasn't made any difference.

I'm using WebApps 2.5, installed from F-Droid, on Android 5.1.1.

**Comment by tobykurien** [comment]
The reason WebApps would kick you out to the default browser is if a site tries to redirect to an non-https site. It might even be that it redirects to an HTTP URL, which then subsequently redirects to an HTTPS URL. What you can then do is to copy the last HTTPS URL an open than URL in WebApps, and then login inside WebApps. Then, if you return to your facebook webapp, it should be logged in.

**Comment by foresto** [comment]
I tried your suggestion, but the redirect URLs go by too fast for me to see, let alone copy & paste. (One of the domains was h.facebook.com, in case that helps.) The last https URL is `https://m.facebook.com/?_rdr`, and when I navigate there directly in WebApps, it just triggers the redirection process again.

**Comment by tobykurien** [comment]
Does this still happen? I tested on my phone and I don't get any redirects - it works fine.

**Comment by foresto** [comment]
>Does this still happen? 

Yes, it still happens, though not every time.  I tried it yesterday and it
worked fine, but I tried it again this evening and got the redirect again. 

Maybe facebook is behaving differently depending on some load balancing
criteria?  At the moment, it's redirecting me when I use the mobile data
network, but letting me in without a redirect when I use wifi.

**Comment by tobykurien** [comment]
It might have something to do with the network you are on, for example if there is a captive portal trying to redirect you for authentication before loading a web page. I'll close this issue as I can't fix this, but if you can reliably replicate this on any network, please re-open.

**Comment by foresto** [comment]
There is no captive portal here. It's just the regular T-Mobile (North America) data network.

I don't think I have the ability to re-open, but I suppose I can post again if I see it happen on a different network.

**Comment by foresto** [comment]
It looks like I can reliably replicate it. The problem appears consistently when I'm on the mobile data network, and disappears when I'm not. (I didn't recognize this pattern at first; I thought it was random.)

**Comment by tobykurien** [comment]
So it seems the network is doing something strange with redirects (much like a captive portal).

**Comment by foresto** [comment]
Maybe, but that seems like a hasty conclusion at this point, given that I've never seen redirects like this on any other site. It could just as easily be facebook.
