### ISSUE TITLE
Use apple-touch-icon instead of favicon as icon

### ISSUE THREAD

**Issue by mueller-ma** [tobykurien/WebApps#57]
Hi,
When you pin a webapp to your homescreen the favicon is used. This might look ok on smart phone, but horrible on tablets.
Firefox is using "apple-touch-icon" instead of favicon. That icon is used, when you pin a website to your home screen on iOS (and also on android): https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

**Comment by mueller-ma** [comment]
@tobykurien When I remove a webapp and save it again, should it than use the touch icon?
I have this from https://github.com/openhab/openhab-core and its still using the favicon:
```
<META HTTP-EQUIV="Content-type" CONTENT="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />

<link rel="shortcut icon" href="images/favicon.ico" />

<link rel="apple-touch-icon" href="images/app-icon.png" />
<link rel="apple-touch-startup-image" href="images/splash-ipad-h.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:landscape)" />
<link rel="apple-touch-startup-image" href="images/splash-ipad-v.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:portrait)" />
<link rel="apple-touch-startup-image" href="images/splash-iphone.png" media="screen and (max-device-width: 320px)" />
```

**Comment by tobykurien** [comment]
It currently uses the highest res favicon that Androids WebView provides. This may or may not be the apple touch icon.

On 6 February 2017 20:11:57 GMT+02:00, mueller-ma <notifications@github.com> wrote:
>@tobykurien When I remove a webapp and save it again, should it than
>use the touch icon?
>I have this from https://github.com/openhab/openhab-core and its still
>using the favicon:
>```
><META HTTP-EQUIV="Content-type" CONTENT="text/html; charset=utf-8">
><meta name="viewport" content="width=device-width, initial-scale=1.0,
>maximum-scale=1.0, user-scalable=0" />
><meta name="apple-mobile-web-app-capable" content="yes" />
><meta name="apple-mobile-web-app-status-bar-style" content="black" />
>
><link rel="shortcut icon" href="images/favicon.ico" />
>
><link rel="apple-touch-icon" href="images/app-icon.png" />
><link rel="apple-touch-startup-image" href="images/splash-ipad-h.png"
>media="screen and (min-device-width: 481px) and (max-device-width:
>1024px) and (orientation:landscape)" />
><link rel="apple-touch-startup-image" href="images/splash-ipad-v.png"
>media="screen and (min-device-width: 481px) and (max-device-width:
>1024px) and (orientation:portrait)" />
><link rel="apple-touch-startup-image" href="images/splash-iphone.png"
>media="screen and (max-device-width: 320px)" />
>```
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/tobykurien/WebApps/issues/57#issuecomment-277765024

-- 
tobykurien.com | @tobykurien

**Comment by mueller-ma** [comment]
Can this behavoir be modified?

**Comment by tobykurien** [comment]
I suppose it is possible to parse the HTML and extract the apple touch icon if it exists, but there are so many ways this can be specified it is not something I'd consider implementing. The newer Chrome-based WebView will probably work.
