### ISSUE TITLE
Untrusted ssl cert exceptions wont be saved

### ISSUE THREAD

**Issue by mueller-ma** [tobykurien/WebApps#58]
Might be a bug or feature.
My problem is: I want a quick way to access a locally hosted webapp. HTTP is not working and a trusted cert is not possible.

**Comment by tobykurien** [comment]
Untrusted cert should work - it will popup and ask if you want to accept the cert once per session.

**Comment by mueller-ma** [comment]
@tobykurien yes, once per session, but not in the next session

**Comment by tobykurien** [comment]
Agreed, which makes this a dup of #29 - all certs should be saved on first access and an alert shown if the cert changes

**Comment by tobykurien** [comment]
Implemented in https://github.com/tobykurien/WebApps/commit/f21f66f94ed550f9d52bc9cbc491f61f0193098f
