### ISSUE TITLE
More configurable third party blocker

### ISSUE THREAD

**Issue by mueller-ma** [tobykurien/WebApps#64]
Currently there is "no third party request on no website" or "everything on every website". This is a problem on sites which load content over other domains controlled by them: e.g. I want to load content from images-website.com,  but no social media buttons

**Comment by mueller-ma** [comment]
My bad. The function is implemented, but I didnt found it. Maybe move it to the menu? The icon doesnt look so clearly

**Comment by tobykurien** [comment]
I did put an explanation on the welcome dialog. I also made the icon show permamently on the action bar so that it isn't hidden in the menu. I agree the icon is not the best. Long-pressing the icons will show you what they do.
