### ISSUE TITLE
More advanced user agent options

### ISSUE THREAD

**Issue by sm4rk0** [tobykurien/WebApps#69]
Available user agents were last updated almost a year and a half ago (05-08-2015), which causes some sites to report that they won't run with WebApps when a user agent different than "Default" is selected.
Some proposals (can be mixed together):

0. Update the current list.

1. Create the user agent string dynamically by changing only some fields from the System WebView UA string and leaving the version unchanged.

2. Allow the user to enter a free-form custom user agent string.

3. Allow the user to "build" a custom user agent string from fixed lists (plus a "custom" option) of operating system (and version), device, browser (and version).

**Comment by tobykurien** [comment]
I agree with the option to add a custom user agent. I've left the old user agents as-is, because most sites support those particular versions differently to anything newer. Twitter and Google News are examples of these - they degrade differently to older versions.
