### ISSUE TITLE
3rd party whitelist not persistent anymore

### ISSUE THREAD

**Issue by guerda** [tobykurien/WebApps#72]
I'm using webapps since several weeks without issues. Since the newest release webapps forgets the 3rd party whitelist each time I start the app. This means I have to unlock all URLs before using it again. This issue occurs in V 2.10

**Comment by tobykurien** [comment]
Is this for saved webapps or only unsaved webapps? I tested on saved webapps and it seems to be working  still?

**Comment by guerda** [comment]
Interesting behaviour. I use saved webapps and access them via shortcuts on the home screen. If I open the apps from the main app, the whitelist is correct. If I use the shortcuts, it's empty. I recreated the shortcuts and now it works again.

Seems like the shortcuts were corrupted by the update?
