### ISSUE TITLE
Enable HTTP (during redirects, e.g. login)

### ISSUE THREAD

**Issue by Eskuero** [tobykurien/WebApps#73]
Could an option to allow HTTP instead of redirecting to another browser be added?
Global or per webapp based it would be welcomed since is almost impossible to login on certain sites which use http pages for redirection between other https whih would go through

**Comment by tobykurien** [comment]
I get you, often you put in a site address and it kicks you out into a browser. If you copy & paste the resulting Url from the browser into WebApps, it should then normally then work (if it is HTTPS). Enabling HTTP is just way too dangerous - if it redirects to an HTTP login page, you wouldn't know. That said, this is common enough that I could look at detecting an HTTPS->HTTP->HTTPS redirect sequence and open the final HTTPS page.

**Comment by Eskuero** [comment]
I was having this login issue with gmail and this webpage https://curiouscat.me/ which is just a dumb question and answers page but I didn't wanted my Twitter logged on my main browser. Copy and pasting the https URL didn't worked, I tried before asking.

I know I can use Gapps browser for gmail and it works nicely but is kinda annoying to have two apps with such similar behaviour to just sandbox three or four webpages.

That being said thanks a lot for your work and the quick answer :)
