### ISSUE TITLE
unable to add Google Maps as a WebApp

### ISSUE THREAD

**Issue by landroni** [tobykurien/WebApps#78]
How can I use Google Maps with WebApps? 

I do not seem to find way to add it to WebApps. I tried to use `Open Site` and go to `maps.google.com`, but Android asks me whether I want to open the address with an external browser (e.g. Firefox or Chrome), but WebApps is not in the list of the proposed programs for completing the action... 

I'm using WebApps 2.11.2 installed from F-Droid, on Android 4.3. (I also tried Google Maps in Gapps, but that app crashes on me often to the point where it's hard to use it reliably.)

**Comment by sm4rk0** [comment]
It's due to redirection.
`maps.google.com` is redirected to `www.google.com/maps` which is then redirected to your country's TLD, in my case (Serbia) `www.google.rs/maps`
Workaround: enter `maps.google.com` in another browser and see where it redirects for you and then enter that URL (with `/maps` part) in WebApps.

**Comment by landroni** [comment]
This worked nicely, thanks. 

I wonder if WebApps could register with Android as a browser so that in such cases of redirect the user could select it. 

Otherwise, it would be nice if Google Maps were provided by default as a WebApp.

**Comment by tobykurien** [comment]
WebApps specifically refuses to handle "http" connections as a way to guarantee that your logged in cookies don't accidentally get send out over an insecure connection. See #73 where I have a plan to handle these redirects without leaking cookies.

I think Google Maps is not a good fit for WebApps - it has the rediection issue, uses many 3rd party domains, and works best with location access. I use openstreetmap.org instead, and when I need it, I use Google Maps on GApps or in the regular browser (without logging in).

**Comment by landroni** [comment]
Makes sense, thanks. 

My big issue with GApps is https://github.com/tobykurien/GoogleApps/issues/32. I also like OsmAnd when using downloaded off-line maps, but for online car navigation I'm still struggling to find a working open-source solution.
