### ISSUE TITLE
Allow to load user scripts/css

### ISSUE THREAD

**Issue by allo-** [tobykurien/WebApps#84]
Is it possible to add loading user scripts or css?

**Comment by tobykurien** [comment]
Should be possible, yes.

**Comment by allo-** [comment]
I would be interested to contribute some user css, i.e. for filtering sponsered posts and from twitter if you add support for injecting css and/or javascript.

**Comment by tobykurien** [comment]
How do you see the user scripts working? User enters URLs to the scripts? User copy & pastes scripts into a dialog? User saves script to sd card and uses system file dialog? All of these have UX issues.

**Comment by allo-** [comment]
A simple text field would be a good start. I guess loading from sd-card would be logical, for most of the other sources it could possibly received from a share intent?
I did not do too much android development yet, so I do especially not know how to get the script itself loaded into a webview.

I do not know how ambitious your goals with the app are.
I could imagine functions where the app can import some data format containing url, domain-whitelist, useragent, user css/scripts and so on which can be installed from some web repository to add a new webapp.
But then the app would of course be quite a bit more than the nice minimalistic app now.

So I guess a simple textarea which stores the script somewhere is a good start for a poweruser feature and can be extended later to be easiert to use if desired.

**Comment by tobykurien** [comment]
After looking into this, it appears this isn't actually possible (security risk). WebView does not allow injecting scripts or CSS. It's possible to work around this by manipulating DOM via javascript execute as a URL load (as per https://stackoverflow.com/questions/30018540/inject-css-to-a-site-with-webview-in-android ) but this it too clunky.
