### ISSUE TITLE
Can't load Movielens

### ISSUE THREAD

**Issue by davidmef** [tobykurien/WebApps#91]
Up until recently I was using https://movielens.org/ from WebApps without much problem, but recently it keeps loading until I get a blank page. I am on 2.13 and I allowed all third party domains: 

- google.com
- uservoice.com
- googleapis.com
- tmdb.org
- gstatic.com
- movielens.org

Could you tell me how to make it work again?
Thanks.

**Comment by tobykurien** [comment]
Webapps v2.13 made a big change to improve cookie sandboxing. Only cookies for the main domain you are visiting is saved. You may need to delete and re-add the site and login again.

**Comment by davidmef** [comment]
I deleted and readded the site. Now it takes a long time to load and presents the login page. I can log in but, if I leave the web application, when I go back, I have to login again. I am using WebApps 2.15 now.
