### ISSUE TITLE
Please allow typing new URLs inside sandboxes

### ISSUE THREAD

**Issue by dluciv** [tobykurien/WebApps#96]
Thank yoy for your great app!

Sometimes I get links to social sites which I want to open in your app, because it is logged in to. I can open new link in it, but such an action opens new sandbox, which is not authenticated.

It would be great to get an option to type/paste URL into existing authenticated sandbox.

**Comment by tobykurien** [comment]
Good suggestion. Issue #93 aims to solve this by allowing you to share the link to WebApps, which will open the right sandbox, but there may be times when a link is not shareable. 

Note that if the link comes from another sandbox, then WebApps will currently open it in the authenticated sandbox.

**Comment by tobykurien** [comment]
While not exactly what you asked for, #93 combined with the new option of `Open in new sandbox` in the URL open dialog allows you to choose how links are opened. By default, it will try to open URLs that are shared or typed in, in an existing sandbox. If more than one sandbox matches, it pops up a selection dialog. If none exist, it opens in a new sandbox. By selecting the `Open in new sandbox` you can force the URL to open in a new sandbox always. 

I am closing this issue as I think this solves it.
