### ISSUE TITLE
crash upon startup on older device with android 4.1

### ISSUE THREAD

**Issue by BrunoKatz** [tobykurien/WebApps#97]
installed WebApps v2.15
via Fdroid on huawei y300 (Android 4.1.1)

When starting the app I see a white screen for a short time then it closes and nothing more.

**Comment by BrunoKatz** [comment]
installed WebApps v2.15 
via Fdroid on huawei y300 (Android  4.1.1)

When starting the app I see a white screen for a short time then it closes and nothing more.

**Comment by tobykurien** [comment]
Error appears to be:

`04-24 20:11:06.239 2478-2478/? E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering
`

This seems to be a bug in support library.
